# Build stage
FROM node:20 as build
WORKDIR /app
COPY book-network-ui/package*.json ./
RUN npm install
COPY book-network-ui/ .
RUN npm run build

# Serve stage
FROM nginx:alpine
COPY --from=build /app/dist/book-network-ui/browser /usr/share/nginx/html
COPY book-network-ui/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
