type: service
name: book-social-network

services:
  - name: backend
    git:
      repository: https://github.com/vipiin/book-social-network
      branch: main
    build:
      dockerfile: Dockerfile.backend
    env:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JDBC_DATABASE_URL
        secret: JDBC_DATABASE_URL
      - key: DB_USERNAME
        secret: DB_USERNAME
      - key: DB_PASSWORD
        secret: DB_PASSWORD
      - key: SPRING_MAIL_HOST
        value: smtp-relay.brevo.com
      - key: SPRING_MAIL_PORT
        value: "587"
      - key: SPRING_MAIL_USERNAME
        secret: BREVO_USER
      - key: SPRING_MAIL_PASSWORD
        secret: BREVO_PASSWORD
      - key: JWT_SECRET
        secret: JWT_SECRET
      - key: CLOUDINARY_CLOUD_NAME
        secret: CLOUDINARY_CLOUD_NAME
      - key: CLOUDINARY_API_KEY
        secret: CLOUDINARY_API_KEY
      - key: CLOUDINARY_API_SECRET
        secret: CLOUDINARY_API_SECRET
      - key: FRONTEND_URL
        value: https://book-social-network-two.vercel.app
    ports:
      - port: 8088
        path: /v1/health
    routes:
      - path: /
        port: 8088

